# Generated by Django 4.1 on 2022-08-09 17:36

from django.db import migrations, models
import recipe.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=models.BooleanField(default=1, verbose_name='Показывать только рецепты, находящиеся в списке избранного.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(default='1', verbose_name='Показывать только рецепты, находящиеся в списке покупок.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[recipe.validators.validate_cooking_time], verbose_name='Время приготовления (в минутах)'),
        ),
    ]
