# Generated by Django 4.1 on 2022-08-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_tags_recipetags_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(max_length=200, verbose_name='Цветовой HEX-код '),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
