# Generated by Django 4.1 on 2022-08-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_tags_color_alter_tags_name_alter_tags_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingerdient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('measurement_unit', models.CharField(max_length=200, verbose_name='Мера')),
            ],
        ),
    ]
