# Generated by Django 4.1 on 2022-08-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe/2022-08-15/'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(max_length=200, verbose_name='Цветовой HEX-код'),
        ),
    ]
