# Generated by Django 4.1 on 2022-08-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_amountingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.CharField(max_length=20, verbose_name='Количество'),
        ),
    ]
