# Generated by Django 4.1 on 2022-08-15 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_alter_amountingredient_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeAmountIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.amountingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe.RecipeAmountIngredient', to='recipe.amountingredient'),
        ),
        migrations.AddField(
            model_name='recipeamountingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
    ]
