# Generated by Django 4.1 on 2022-08-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_recipe_ingredient_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountingredient',
            name='recipe',
            field=models.ForeignKey(default=2,
                                    on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='recipes', through='recipe.AmountIngredient', to='recipe.ingredient'),
        ),
    ]
