# Generated by Django 4.1 on 2022-08-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_amountingredient_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipe.AmountIngredient', to='recipe.ingredient'),
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
