# Generated by Django 4.1 on 2022-08-16 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_remove_recipe_ingredient_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингридиентов 1')], verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient', verbose_name='Ингридиент')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeamountingredient',
            name='amount_ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeamountingredient',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipe.IngredientAmount', to='recipe.ingredient', verbose_name='Ингридиенты'),
        ),
        migrations.DeleteModel(
            name='AmountIngredient',
        ),
        migrations.DeleteModel(
            name='RecipeAmountIngredient',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Рецепт'),
        ),
    ]
